/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BotTag {
    }
    interface FeedbackTag {
        "_id": any;
    }
    interface MainTag {
        "_id": any;
    }
    interface MyComponent {
        "_id": any;
        /**
          * The first name
         */
        "first": string;
        "header": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyTheme {
        "_id": any;
    }
}
declare global {
    interface HTMLBotTagElement extends Components.BotTag, HTMLStencilElement {
    }
    var HTMLBotTagElement: {
        prototype: HTMLBotTagElement;
        new (): HTMLBotTagElement;
    };
    interface HTMLFeedbackTagElement extends Components.FeedbackTag, HTMLStencilElement {
    }
    var HTMLFeedbackTagElement: {
        prototype: HTMLFeedbackTagElement;
        new (): HTMLFeedbackTagElement;
    };
    interface HTMLMainTagElement extends Components.MainTag, HTMLStencilElement {
    }
    var HTMLMainTagElement: {
        prototype: HTMLMainTagElement;
        new (): HTMLMainTagElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyThemeElement extends Components.MyTheme, HTMLStencilElement {
    }
    var HTMLMyThemeElement: {
        prototype: HTMLMyThemeElement;
        new (): HTMLMyThemeElement;
    };
    interface HTMLElementTagNameMap {
        "bot-tag": HTMLBotTagElement;
        "feedback-tag": HTMLFeedbackTagElement;
        "main-tag": HTMLMainTagElement;
        "my-component": HTMLMyComponentElement;
        "my-theme": HTMLMyThemeElement;
    }
}
declare namespace LocalJSX {
    interface BotTag {
    }
    interface FeedbackTag {
        "_id"?: any;
    }
    interface MainTag {
        "_id"?: any;
    }
    interface MyComponent {
        "_id"?: any;
        /**
          * The first name
         */
        "first"?: string;
        "header"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyTheme {
        "_id"?: any;
    }
    interface IntrinsicElements {
        "bot-tag": BotTag;
        "feedback-tag": FeedbackTag;
        "main-tag": MainTag;
        "my-component": MyComponent;
        "my-theme": MyTheme;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bot-tag": LocalJSX.BotTag & JSXBase.HTMLAttributes<HTMLBotTagElement>;
            "feedback-tag": LocalJSX.FeedbackTag & JSXBase.HTMLAttributes<HTMLFeedbackTagElement>;
            "main-tag": LocalJSX.MainTag & JSXBase.HTMLAttributes<HTMLMainTagElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-theme": LocalJSX.MyTheme & JSXBase.HTMLAttributes<HTMLMyThemeElement>;
        }
    }
}
